# Generated by Django 2.2.5 on 2019-10-11 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegister', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата реєстрації')),
                ('dateArrival', models.DateTimeField(blank=True, null=True, verbose_name='Очікуємое время начала розвантження')),
                ('dateUpload', models.DateTimeField(blank=True, null=True, verbose_name='Дата розвантаження')),
                ('timeProc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Хвилин на розвантаження')),
                ('status', models.CharField(choices=[('Ожидание', 'Ожидание'), ('Завантажений', 'Завантажений'), ('Відправлен', 'Відправлен')], default='Ожидание', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Розвантаження',
                'verbose_name_plural': 'Розвантаження',
            },
        ),
    ]
