# Generated by Django 2.2.5 on 2019-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Назва техники')),
                ('timeUse', models.IntegerField(blank=True, null=True, verbose_name='Хвилин использования за сегодня')),
                ('HoursDay', models.IntegerField(blank=True, null=True, verbose_name='Норма годин в день')),
                ('allHours', models.IntegerField(blank=True, null=True, verbose_name='Ресурс использования')),
                ('typeTransport', models.CharField(choices=[('Сухі товари', 'Сухі товари'), ('Швидко псуються товари', 'Швидко псуються товари'), ('Крихкі товари', 'Крихкі товари')], default='Сухі товари', max_length=30, verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
