# Generated by Django 2.2.5 on 2019-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190921_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Відправлен', 'Відправлен'), ('У обробці', 'У обробці'), ('Прийнятий', 'Прийнятий'), ('Скасований', 'Скасований')], default='Відправлен', max_length=30, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='typeProduct',
            field=models.CharField(choices=[('Сухі товари', 'Сухі товари'), ('Швидко псуються товари', 'Швидко псуються товари'), ('Крихкі товари', 'Крихкі товари')], default='Сухі товари', max_length=30, verbose_name='Тип продукта'),
        ),
    ]
